version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  server---auth:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "3090:3090"
    volumes:
      - /app/node_modules
      - ./:/app
    links:
      - mongo